name: Cli Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 10.x]
    steps:
      - name: Checkout cli repo
        uses: actions/checkout@v2
      - run: source .github/scripts/trigger-and-wait.sh
        env:
          owner: ravali-rimmalapudi
          repo: twilio-cli
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: docker-release.yml
          ref: main
          wait_interval: 10
          trigger_workflow: true
          wait_workflow: true
