name: Cli Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cli repo
        uses: actions/checkout@v2
      - run: source .github/scripts/trigger-and-wait.sh
        env:
          INPUT_OWNER: ravali-rimmalapudi
          INPUT_REPO: twilio-cli
          INPUT_GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          INPUT_WORKFLOW_FILE_NAME: docker-release.yml
          INPUT_REF: main
          INPUT_WAITING_INTERVAL: 10
          INPUT_TRIGGER_WORKFLOW: true
          INPUT_WAIT_WORKFLOW: true
