name: Final Build

on:
  workflow_dispatch:
  workflow_run:
    # wait for Cli Release to complete, when it completes, start this workflow 
    workflows: 
      - Docker Hub Release
    branches: [main]
    types: 
      - completed
jobs:
  dummy:
    name: Dummy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: docker-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Docker Hub Release
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: oclif-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Oclif Release
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Do something with a passing build
        if: steps.docker-release.outputs.conclusion == 'success' && steps.oclif-release.outputs.conclusion == 'success'
        run: echo "Done"

