name: Oclif Release
on:
  workflow_dispatch:
    inputs:
      home-brew-branch:
        description: 'Run workflow in home brew branch'
        default: main
      tag-name:
        description: 'Tag to be released in Homebrew (Same as CLI latest tag name)'
        required: true
      formula:
          description: 'Formula to release in homebrew'
          default: twilio
      pre-release:
        description: 'Homebrew release type'
        default: 'false'
jobs:
  dummy:
    name: Dummy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#   oclif-release:
#     name: Publish for ${{ matrix.os }}
#     runs-on: ${{ matrix.os }}
#     outputs:
#       sha256: ${{ steps.sha256.outputs.sha256 }}
#     strategy:
#       fail-fast: false
#       matrix:
#         include:
#           - os: macos-latest
#             asset_name: ${{ github.event.inputs.formula }}-v${{ github.event.inputs.tag-name }}
#             command_name: npx oclif-dev pack
#             publish: homebrew
#     steps:
#       - uses: actions/checkout@v2
#       - run: |
#           npm install
#           if [ "$RUNNER_OS" == "macOS" ]; then
#             brew install makensis
#           fi
#           ${{ matrix.command_name }}
#       - name: Configure AWS credentials from Test account
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#           aws-region: us-east-1
#       - name: Publish assests to s3 and calculate sha of oclif dev pack
#         id: sha256
#         if: ${{matrix.publish == 'homebrew'}}
#         run: |
#            npx oclif-dev publish
#            brew install coreutils
#            echo "::set-output name=sha256::$(sha256sum dist/${{ matrix.asset_name }}/${{ matrix.asset_name }}.tar.gz | awk '{print $1}')"
  home-brew-release:
    name: Trigger homebrew release workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cli repo
        uses: actions/checkout@v2
      - name: Invoke HomeBrew workflow
        run: source .github/scripts/trigger-and-wait.sh
        env:
          INPUT_OWNER: ravali-rimmalapudi
          INPUT_REPO: homebrew-brew
          INPUT_GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          INPUT_WORKFLOW_FILE_NAME: release.yml
          INPUT_REF: ${{ github.event.inputs.home-brew-branch }}
          INPUT_WAITING_INTERVAL: 10
          INPUT_INPUTS: '{ "formula": "${{github.event.inputs.formula}}", "version": "${{github.event.inputs.tag-name}}", "sha": "${{needs.oclif-release.outputs.sha256}}", "pre-release": "${{github.event.inputs.pre-release}}" }'
          INPUT_PROPAGATE_FAILURE: true
          INPUT_TRIGGER_WORKFLOW: true
          INPUT_WAIT_WORKFLOW: true
