name: twilio deb
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cli repo
        uses: actions/checkout@v2
      - name: Install twilio cli through .deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download 2.31.0 --pattern '*.deb'
          sudo dpkg -i twilio-2.31.0.deb
          twilio --version
