name: twilio Docker
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - run: |
          docker pull twilio/twilio-cli
          twilio --version
