name: twilio Docker
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker pull twilio/twilio-cli
      - uses: docker://twilio/twilio-cli:latest
        with:
          entrypoint: /usr/bin/bash
          args: -c 'twilio --version'
